import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' min-h-screen bg-gradient-to-b from-purple-400 to-pink-500 flex items-center justify-center p-4 overflow-hidden'}>{children}</body>
    </html>
  );
}
